### ISSUE TITLE
Can't understand what those parameters exactly mean, plz give example or doc.

### ISSUE THREAD

**Issue by zhenpingfeng** [ihciah/shadow-tls#1]
```
./shadow-tls server 0.0.0.0:8443 xxx.com:443 xxx.com
./shadow-tls client 0.0.0.0:1084 xxx.com:8443 xxx.com
```

client_log:
```
2022-08-25T13:42:09.836466Z  INFO shadow_tls::protocol: tcp connected, start handshaking
2022-08-25T13:42:14.234668Z  INFO shadow_tls: Accepted a connection from 127.0.0.1:50384
2022-08-25T13:42:14.245772Z  INFO shadow_tls: Accepted a connection from 127.0.0.1:50386
2022-08-25T13:42:14.340122Z  INFO shadow_tls::protocol: tcp connected, start handshaking
```
server_log:
```
2022-08-25T13:42:07.928400Z  INFO shadow_tls: Accepted a connection from client_ipv4:26623
2022-08-25T13:42:07.935882Z  INFO shadow_tls: Accepted a connection from client_ipv4:26622
```

no error and seem connection successfully but can't access censored website. browser response ERR_CONNECTION_RESET

**Comment by ihciah** [comment]
This is something like simple-obfs. Maybe you need a shadowsocks or tinc to make it work.
Here is a sample server:
```yaml
version: '2.4'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks-raw
    restart: always
    network_mode: "host"
    environment:
      - SERVER_PORT=24000
      - SERVER_ADDR=127.0.0.1
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=EXAMPLE_PASSWORD_CHANGE_IT
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: always
    network_mode: "host"
    environment:
      - MODE=server
      - LISTEN=0.0.0.0:8443
      - SERVER=127.0.0.1:24000
      - TLS=cloud.tencent.com:443
```

And the client side(you can deploy it in your private network or vps inside the country):
```
version: '2.4'
services:
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: always
    network_mode: "host"
    environment:
      - MODE=client
      - LISTEN=0.0.0.0:3443
      - SERVER=your_vps_ip:8443
      - TLS=cloud.tencent.com
```

Then use shadowsocks client to connect cn_vps:3443 will work.
