### ISSUE TITLE
I want Shadowtls to work with Trojan sever

### ISSUE THREAD

**Issue by captainstdin** [ihciah/shadow-tls#114]
this is docker-compose.yaml

```yaml

version: '3.3'
services:
  trojan:
    image: p4gefau1t/trojan-go
    container_name: trojan
    restart: always
    depends_on:
      - webpage
    volumes:
      - ./:/config/
    ports:
      - '443:443'
    command: /config/config.json
  webpage:
    image: wikihostinc/looking-glass-server:latest
    restart: always
    environment:
      - "UTILITIES_FAKESHELL=false"
      - "UTILITIES_IPERF3=false"
      - "SPONSOR_MESSAGE= test mirrors"
    ports:
      - '80:80'
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    container_name: shadow-tls
    restart: always
    ports:
      - 8080:8080
    environment:
      - V3=1
      - MODE=server
      - LISTEN=0.0.0.0:8080
      - SERVER=trojan:443
      - TLS=www.baidu.com;www.qq.com
      - PASSWORD=010110
```
It's  not work

## Do I need to enable this function?

https://p4gefau1t.github.io/trojan-go/advance/plugin/
