### ISSUE TITLE
构建DOCKER镜像，版本号不对？

### ISSUE THREAD

**Issue by hzqim** [ihciah/shadow-tls#24]
使用作者的Docker v0.2.1 镜像进行测试，没有成功转发。
看到前面有朋友说0.1.4能成功转发，0.2.1却不能，于是试着 clone 了 0.1.4 源码进行构建 Docker 镜像。
虽然顺利构建但在容器中发现  shadow-tls 版本号为 0.1.0。

**Comment by ihciah** [comment]
目前我这边尚未确定 0.2 版本的不能转发的问题原因，可以贴下你的系统版本吗(uname -a)？
0.1.0 那个无所谓的，以 git tag 为准。

**Comment by hzqim** [comment]
VPS防火墙已放行端口。

Router

1. uname -a

```
root@OpenWrt:uname -a
Linux OpenWrt 5.10.138 #0 SMP PREEMPT Sat Sep 3 02:55:34 2022 aarch64 GNU/Linux
```

2. shadowsocks:

```config servers
        option fast_open '0'
        option no_delay '0'
        option timeout '60'
        option password 'Goodluck4ever'
        option encrypt_method 'chacha20-ietf-poly1305'
        option alias 'shadow-tls'
        option server_port '3080'
        option server '127.0.0.1'
```
3. docker-compose.yml
```
version: '2.4'
services:
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    container_name: shadow-tls
    restart: always
    network_mode: "host"
    environment:
      - MODE=client
      - LISTEN=0.0.0.0:3080
      - SERVER=remote:2080
      - TLS=www.apple.com
      - PASSWORD=Goodluck4ever
      - MONOIO_FORCE_LEGACY_DRIVER=1
```

SERVER

1. uname -a
```
root@ip-172-31-15-191:/home/docker/shadow-tls# uname -a
Linux ip-172-31-15-191 5.15.0-1020-aws #24~20.04.1-Ubuntu SMP Fri Sep 2 15:29:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
2. shadow-tls docker-compose.yml
```
version: '2.4'
services:
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    container_name: shadow-tls
    restart: always
    environment:
      - MODE=server
      - LISTEN=0.0.0.0:2080
      - SERVER=ssnew:8388
      - TLS=www.apple.com:443
      - PASSWORD=Goodluck4ever
        #      - MONOIO_FORCE_LEGACY_DRIVER=1 
    networks:
      - vps
    ports:
      - "2080:2080"

networks:
  vps:
    external: true
```
3. shadowsocks docker-compose.yml
```
version: '3.3'
services:
  ssnew:
    container_name: ssnew
    image: teddysun/shadowsocks-libev
    volumes: 
      - .:/etc/shadowsocks-libev
    restart: unless-stopped
    networks: 
      - vps

networks:
  vps:
    external: true
```
4. shadowsocks config.json
```
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"Goodluck4ever",
    "timeout":300,
    "method":"chacha20-ietf-poly1305",
    "fast_open":false,
    "nameserver":"8.8.8.8",
    "mode":"tcp_only"
}
```
