### ISSUE TITLE
修改了一下wiki里的compose部分

### ISSUE THREAD

**Issue by rayer4u** [ihciah/shadow-tls#70]
目前个人觉得可以改进的几个地方
1. 不采用host网络，尽量少的暴露端口
2. 补充了客户端的shadowsocks部分，并统一相关配置（这里是shadowsocks-libev镜像根本没考虑client部分，不采用额外配置文件的情况下，个人感觉这样最统一），这样也有socks5h proxy使用了
3. 明确最小修改项，只用替换几处，就能直接使用。后续可能变更的只有映射的port和TLS
4. 采用了compose 3，更成熟、方便

```
## Example Compose Files
Here is a sample server(a shadowsocks with a shadow-tls), user only need to replace `EXAMPLE_PASSWORD_SS`, `EXAMPLE_PASSWORD_ST`, run it on your remote vps:

```yaml
version: '3.5'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    restart: always
    command: /bin/sh -c 'exec ss-server -s 0.0.0.0 -p 24000 -k EXAMPLE_PASSWORD_SS -m chacha20-ietf-poly1305 -t 300'
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: always
    ports:
      - "8443:8443"
    environment:
      - MODE=server
      # - V3=1
      - LISTEN=0.0.0.0:8443
      - SERVER=shadowsocks:24000
      - TLS=cloud.tencent.com:443
      - PASSWORD=EXAMPLE_PASSWORD_ST
    depends_on:
      - shadowsocks
```

And the client side(you can deploy it in your private network or vps inside the country), replace `EXAMPLE_PASSWORD_SS`, `EXAMPLE_PASSWORD_ST`, `YOUR_VPS_IP` with yours like above:

```yaml
version: '3.5'
services:
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: always
    ports:
      - "3443:3443"
    environment:
      - MODE=client
      # - V3=1
      - LISTEN=0.0.0.0:3443
      - SERVER=YOUR_VPS_IP:8443
      - TLS=cloud.tencent.com
      - PASSWORD=EXAMPLE_PASSWORD_ST
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    restart: always
    command: /bin/sh -c 'exec ss-local -b 0.0.0.0 -l 1080 -s shadow-tls -p 3443 -k EXAMPLE_PASSWORD_SS -m chacha20-ietf-poly1305 -t 300'
    ports:
      - "1080:1080"
    depends_on:
      - shadow-tls
```

Then connect `cn_vps:3443` with shadowsocks protocol on your mobile phones or PCs will work or connect `cn_vps:1080` with sock5h protocol on browser proxy.
```
