### ISSUE TITLE
an idea of docker support for armv7

### ISSUE THREAD

**Issue by Kosette** [ihciah/shadow-tls#87]
as `rust:alpine` doesn't support armv7, so there's no way to build image for it from scratch. But I see there's precompiled excutable for armv7 in github release, so think we can build image using it directly.

example Dockerfile as below:
```Dockerfile
FROM alpine:latest

ENV MODE=""
ENV LISTEN=""
ENV SERVER=""
ENV TLS=""
ENV THREADS=""
ENV PASSWORD=""
ENV ALPN=""
ENV DISABLE_NODELAY=""
ENV V3=""
ENV STRICT=""

COPY ./entrypoint.sh /
ADD https://github.com/ihciah/shadow-tls/releases/latest/download/shadow-tls-armv7-unknown-linux-musleabihf /usr/local/bin/shadow-tls
RUN chmod +x /usr/local/bin/shadow-tls && chmod +x /entrypoint.sh && apk add --no-cache ca-certificates
ENTRYPOINT ["/entrypoint.sh"]
```
I've tested it, as far as i know it works well. the only risk is that we must have a latest github release first, i don't know much about github actions, so i'm not sure whether it is a problem.

and if we build image this way for armv7 alone, it needs an extra tag. as i know we can offer multi architecture images in same tag using `docker manifest`, but i don't know how to implement it in a github action way, or we could use `RUN` which i do not like it at all.

after all, just take it as a feasible idea to using shadow-tls docker container for those docker lovers like me.😄

**Comment by ihciah** [comment]
Thanks! I will try it soon.

**Comment by Kosette** [comment]
just did some research. we could use one single Dockerfile that downloading executables depending on target platform. as exe for armv7 naming with `musleabihf`, we may need some dirty tricks. one solution may like this:
```
FROM alpine:latest as builder

WORKDIR /app
COPY ./arch.txt .
RUN apk add --no-cache curl &&\
    grep $(uname -m) ./arch.txt |\
    awk '{print$2}' |\
    xargs -I{} curl -L "https://github.com/ihciah/shadow-tls/releases/latest/download/shadow-tls-{}" -o ./shadow-tls

FROM alpine:latest

ENV MODE=""
ENV LISTEN=""
ENV SERVER=""
ENV TLS=""
ENV THREADS=""
ENV PASSWORD=""
ENV ALPN=""
ENV DISABLE_NODELAY=""
ENV V3=""
ENV STRICT=""

COPY ./entrypoint.sh /
COPY --from=builder /app/shadow-tls /usr/local/bin/shadow-tls
RUN chmod +x /usr/local/bin/shadow-tls && chmod +x /entrypoint.sh && apk add --no-cache ca-certificates
ENTRYPOINT ["/entrypoint.sh"]
```
a external `arch.txt` contains keywords like:
```
armv7l armv7-unknown-linux-musleabihf
aarch64 aarch64-unknown-linux-musl
x86_64 x86_64-unknown-linux-musl
```
now we can keep build-docker-image.yaml like this:
```
name: Build Docker Images
on:
……

env:
  IMAGE_NAME: shadow-tls

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and release Docker images 
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          push: true
```
the building process is really fast for about less than 1min. 

---------
as mentioned above, building docker images must follow building release. good news is that we have two methods:
1. write 2 jobs in one yaml, first building releases then images;
2. seperate in 2 yamls, set the trigger of build-docker-images.yaml like this:
```
on:
  workflow_run:
    workflows: ["Build Releases"]
    types:
      - completed
```
reference: https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
