### ISSUE TITLE
自动更新镜像后一直报错无法启动

### ISSUE THREAD

**Issue by wxywizard** [ihciah/shadow-tls#88]
image：ghcr.io/ihciah/shadow-tls:latest

错误信息
```
shadow-tls  | /usr/local/bin/shadow-tls: line 1: Not: not found
```
docker-compose.yml
```
  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    container_name: shadow-tls
    restart: always
    network_mode: "host"
    environment:
      - MODE=server
      - V3=1
      - LISTEN=
      - SERVER=
      - TLS=
      - PASSWORD=
```
